export const codingHeroes = [
  {
    name: 'LoopMaster',
    superPower: 'Infinite For Loops',
    language: 'JavaScript',
    level: 7,
    emoji: '🌀',
    hasCape: true,
  },
  {
    name: 'NullPointer',
    superPower: 'Debugs with a glance',
    language: 'Java',
    level: 9,
    emoji: '🧠',
    hasCape: false,
  },
  {
    name: 'CSSiren',
    superPower: 'Can center anything',
    language: 'CSS',
    level: 10,
    emoji: '🎯',
    hasCape: true,
  },
  {
    name: 'StackQueen',
    superPower: 'Answers all StackOverflow questions',
    language: 'Python',
    level: 8,
    emoji: '👑',
    hasCape: true,
  },
  {
    name: 'GitWitch',
    superPower: 'Reverts mistakes with a spell',
    language: 'Git',
    level: 6,
    emoji: '🧙‍♀️',
    hasCape: false,
  },
  {
    name: 'BugZapper',
    superPower: 'Squashes 10 bugs with one commit',
    language: 'Ruby',
    level: 5,
    emoji: '⚡',
    hasCape: false,
  },
  {
    name: 'ReactRanger',
    superPower: 'Tames the Virtual DOM',
    language: 'React',
    level: 9,
    emoji: '🤠',
    hasCape: true,
  },
];
